version: "2"
services:
  node:
    image: node:6
    working_dir: /ueberDB
    command: bash -c "npm install && node_modules/mocha/bin/mocha tests/"
    volumes:
      - ./ueberDB:/ueberDB
    links:
      - db

  db:
    image: mongo
    volumes:
      - /data/db
    expose:
      - "27017"
